import { ofetch } from "ofetch";

await ofetch("http://localhost:3000/api/zettle/webhook", {
  method: "POST",
  body: {
    organizationUuid: "d3f03ffa-4a18-4282-bbfa-efd5f642ffb7",
    messageUuid: "803f68c0-a110-11eb-a1cd-f7dd79ee0866",
    eventName: "PurchaseCreated",
    messageId: "2895af2a-faba-5f51-a1cd-f7dd79ee0866",
    payload:
      '{"purchaseUuid":"7cdf4ae2-a110-11eb-a7f9-24cfef8c2970","source":"POS","userUuid":"7a1abbf4-b5e2-4c70-8b21-f4ec5b00c463","currency":"GBP","country":"GB","amount":35300,"vatAmount":3656,"timestamp":1618837780798,"created":"2021-04-19T13:09:40.798+0000","gpsCoordinates":{"longitude":18.11516501942474,"latitude":59.31182861328125,"accuracyMeters":14.014972079943288},"purchaseNumber":12776,"userDisplayName":"John Smith","udid":"692e074e16fb8e99cafbce1c975582c1ce8dbd8f","organizationUuid":"d3f03ffa-4a18-4282-bbfa-efd5f642ffb7","products":[{"id":"0","productUuid":"4a98a670-7c2e-11eb-bb38-e398536ff6aa","variantUuid":"4a98a671-7c2e-11eb-bb38-e398536ff6aa","name":"testproduct","variantName":"","sku":"987","unitPrice":1200,"quantity":"2","vatPercentage":0.0,"taxRates":[{"percentage":0}],"taxExempt":false,"fromLocationUuid":"fd4a39a0-e2ef-11e6-ba64-85247ae2a737","toLocationUuid":"fd4a87c0-e2ef-11e6-bfe3-78ba29c12242","autoGenerated":false,"type":"PRODUCT","details":{}},{"id":"1","productUuid":"ffa4e654-987c-11eb-bd32-b9ba7d636d99","variantUuid":"018ff152-987d-11eb-8147-faacf6e11cc8","name":"Whiskey","variantName":"50 cm","sku":"The Whiskey - Small","barcode":"30955168623","unitPrice":32900,"costPrice":0,"quantity":"1","vatPercentage":12.5,"taxRates":[{"percentage":12.5}],"taxExempt":false,"fromLocationUuid":"fd4a39a0-e2ef-11e6-ba64-85247ae2a737","toLocationUuid":"fd4a87c0-e2ef-11e6-bfe3-78ba29c12242","autoGenerated":false,"type":"PRODUCT","details":{}}],"discounts":[],"payments":[{"uuid":"8031c38c-a110-11eb-a6f8-25ceee8d2871","amount":35300,"type":"IZETTLE_CASH","attributes":{"changeAmount":0,"handedAmount":35300}}],"references":{"checkoutUUID":"7cdf4ae2-a110-11eb-a6f8-25ceee8d2871"},"taxationMode":"INCLUSIVE","taxationType":"VAT"}',
    timestamp: "2021-04-19T13:09:40.812Z",
  },
});
