name: "[frontend] build -> push -> deploy"
on:
  push:
    branches: [main]
    paths:
      - frontend/**
      - .github/workflows/deploy.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-frontend:
    permissions:
      contents: read
      packages: write
    uses: TIHLDE/tihlde-workflows/.github/workflows/_ci_ghcr.yml@main
    with:
      context: .
      dockerfile: ./Dockerfile.frontend
      image_name: "drift-frontend"

  deploy-frontend:
    needs: build-frontend
    if: github.event_name != 'pull_request'
    uses: TIHLDE/tihlde-workflows/.github/workflows/_notify_deploy.yml@main
    with:
      image_name: "drift-frontend"
    secrets:
      DEPLOY_RECEIVER_TOKEN: ${{ secrets.DEPLOY_RECEIVER_TOKEN }}
